# Generated by Django 5.1.4 on 2024-12-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_consumer_content_alter_consumer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('type_of_disease', models.CharField(max_length=100)),
                ('natural_fertilizer', models.TextField()),
                ('suggestion', models.TextField()),
                ('recommendation', models.TextField()),
            ],
        ),
    ]
