# Generated by Django 5.1.4 on 2024-12-09 22:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_plantdisease'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('image_hash', models.CharField(max_length=64, unique=True)),
                ('prediction', models.CharField(max_length=255)),
                ('detection_info', models.TextField()),
                ('suggestion', models.TextField()),
                ('recommendation', models.TextField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
