# Generated by Django 5.1.4 on 2024-12-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_imageprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprediction',
            name='fertilizer',
            field=models.TextField(null=True),
        ),
    ]
