# Generated by Django 5.1.4 on 2024-12-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_imageprediction_fertilizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprediction',
            name='image',
            field=models.ImageField(null=True, upload_to='uploaded_images/'),
        ),
    ]
